In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [2]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]

In [4]:
x = np.array(x)
y = np.array(y)

In [5]:
x.shape

(8, 2)

In [7]:
y.shape

(8,)

In [8]:
model = LinearRegression().fit(x,y)

In [9]:
r_sq = model.score(x, y)
print(r_sq)

0.8615939258756776


In [10]:
print(model.intercept_)
print(model.coef_)

5.52257927519819
[0.44706965 0.25502548]


In [11]:
y_est = model.predict(x)

In [12]:
y_est, y

(array([ 5.77760476,  8.012953  , 12.73867497, 17.9744479 , 23.97529728,
        29.4660957 , 38.78227633, 41.27265006]),
 array([ 4,  5, 20, 14, 32, 22, 38, 43]))

In [13]:
x_new = np.arange(10).reshape((-1,2))
print(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
y_new_pred = model.predict(x_new)

In [34]:
y_new_pred

array([ 5.77760476,  7.18179502,  8.58598528,  9.99017554, 11.3943658 ])