In [1]:
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [3]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [4]:
x_ = transformer.fit_transform(x)
print(x_)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]


In [5]:
model = LinearRegression().fit(x_, y)

In [6]:
print(model.intercept_)
print(model.coef_)

21.37232142857144
[-1.32357143  0.02839286]


In [7]:
r_sq = model.score(x_, y)
print(r_sq)

0.8908516262498564


In [8]:
y_est = model.predict(x_)
print(y - y_est)

[-0.46428571  3.09285714 -4.02857143 -1.82857143  5.69285714 -2.46428571]


In [9]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x = np.array(x)
y = np.array(y)

In [10]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)
print(x_)

[[0.000e+00 1.000e+00 0.000e+00 0.000e+00 1.000e+00]
 [5.000e+00 1.000e+00 2.500e+01 5.000e+00 1.000e+00]
 [1.500e+01 2.000e+00 2.250e+02 3.000e+01 4.000e+00]
 [2.500e+01 5.000e+00 6.250e+02 1.250e+02 2.500e+01]
 [3.500e+01 1.100e+01 1.225e+03 3.850e+02 1.210e+02]
 [4.500e+01 1.500e+01 2.025e+03 6.750e+02 2.250e+02]
 [5.500e+01 3.400e+01 3.025e+03 1.870e+03 1.156e+03]
 [6.000e+01 3.500e+01 3.600e+03 2.100e+03 1.225e+03]]


In [11]:
model = LinearRegression().fit(x_, y)

In [12]:
print('r_sq = ', model.score(x_,y))

r_sq =  0.9453701449127822


In [13]:
print('b_0 = ', model.intercept_)
print('[b_1,b_2,b_3,b_4,b_5] = ', model.coef_)

b_0 =  0.8430556452395876
[b_1,b_2,b_3,b_4,b_5] =  [ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]
